### ISSUE TITLE
是失效了吗还是我的配置问题？

### ISSUE THREAD

**Issue by LiuZHolmes** [Attt/Anyproxy-fgo-rule#3]
iOS客户端，Anyproxy是用Mac配置的。
log里看到应该代理服务工作是正常的：
```
[AnyProxy Log][2018-05-27 16:00:14]: [internal https]proxy server for static.biligame.net established
[AnyProxy Log][2018-05-27 16:00:14]: received https CONNECT request pinterface.biligame.net
[AnyProxy Log][2018-05-27 16:00:14]: will forward to local https server
[AnyProxy Log][2018-05-27 16:00:14]: [internal https]proxy server for pinterface.biligame.net established
[AnyProxy Log][2018-05-27 16:00:14]: received request to: HEAD p.biligame.com/api/client/verify_channel?&
[AnyProxy Log][2018-05-27 16:00:14]: received request to: GET p.biligame.com/api/client/config?************************************
[AnyProxy Log][2018-05-27 16:00:15]: received https CONNECT request line3-s2-ios-fate.bilibiligame.net
[AnyProxy Log][2018-05-27 16:00:15]: will forward to local https server
[AnyProxy Log][2018-05-27 16:00:15]: [internal https]proxy server for line3-s2-ios-fate.bilibiligame.net established
[AnyProxy Log][2018-05-27 16:00:15]: received https CONNECT request line1-s2-ios-fate.bilibiligame.net
[AnyProxy Log][2018-05-27 16:00:15]: will forward to local https server
```
但是手机里打开游戏时提示“与服务器连接中断”
手机和电脑上的证书都已经信任了。

**Comment by LiuZHolmes** [comment]
emm找到问题了，iOS10.3以上版本信任证书后还需要在“关于本机”里打开证书。
但还是会经常遇到这样的错误
```
[AnyProxy ERROR][2018-05-27 16:36:52]: got an uncaught exception, is there anything goes wrong in your rule file ?
Error: read ECONNRESET
    at TCP.onread (net.js:659:25)
[AnyProxy Log][2018-05-27 16:36:52]: destorying https connection : 127.0.0.1:59579
[AnyProxy Log][2018-05-27 16:36:52]: endding https cltSocket : 127.0.0.1:59579
[AnyProxy Log][2018-05-27 16:36:52]: clearing cache file...
[AnyProxy Log][2018-05-27 16:36:52]: closing webserver...

**Comment by LiuZHolmes** [comment]
另外在退出游戏重进战斗的时候会报错：
```
[AnyProxy Log][2018-05-27 16:34:21]: received request to: POST line3-s2-ios-fate.bilibiligame.net/rongame_beta/rgfate/60_1001/ac.php?_userId=100108478765
[AnyProxy ERROR][2018-05-27 16:34:22]: TypeError: Cannot read property 'battle' of undefined
TypeError: Cannot read property 'battle' of undefined
    at Object.beforeSendResponse (/Users/retr0/Downloads/Anyproxy-fgo-rule-master/fgo.js:27:52)
    at beforeSendResponse.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/anyproxy/node_modules/co/index.js:65:19)
    at /usr/local/lib/node_modules/anyproxy/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/usr/local/lib/node_modules/anyproxy/node_modules/co/index.js:50:10)
    at toPromise (/usr/local/lib/node_modules/anyproxy/node_modules/co/index.js:118:63)
    at next (/usr/local/lib/node_modules/anyproxy/node_modules/co/index.js:99:29)
    at onFulfilled (/usr/local/lib/node_modules/anyproxy/node_modules/co/index.js:69:7)
    at /usr/local/lib/node_modules/anyproxy/node_modules/co/index.js:54:5

不知道是不是battleresume的包头部改过了还是？qwq

**Comment by ZizhuoWang** [comment]
我安卓，新建战斗和战斗重开我都试了试，没啥问题。。。另外你最好把涉及到你的userId的部分修改掉，防止万一有闲的B站人员看见了把你封了就GG了。。。

**Comment by Attt** [comment]
@LiuZHolmes 
1) 因为当时手边没有IPHONE，所以IOS没有做过测试😳，重进战斗出现的问题可能是响应内容和安卓的有所不同，具体的要抓包看，做对应的修改。
2) read ECONNRESET 这个问题话，具体是在什么情况下出现的，安卓没有遇到过这个问题，不过我猜想应该是部分请求造成的（比如bin文件下载），因为实际使用的时候我只代理了部分请求（战斗相关的），你可以尝试一下使用pac。😀
ps. 贴Log的时候不要轻易把请求参数带上，万一翻车了。。我已经把你的信息脱敏了。

**Comment by LiuZHolmes** [comment]
@ZizhuoWang 哈哈好的，因为是用小号测试的就没太注意了。

**Comment by LiuZHolmes** [comment]
@Attt 
1.  可能是iOS的包有些不同，我有空抓个看看能不能看到它的battle属性。
2.  会不会是其他进程的网络请求造成的？错误出现前的连接请求是不固定的，有可能是chrome的或者是iTunes的请求之类的，这个会有影响吗？

我已经改了log里的id了xD

**Comment by LiuZHolmes** [comment]
重开战斗的问题没有重现了，抓包发现属性值和安卓的一样。
pac过滤*biligame.net*偶尔还会出现同样的错误退出。

**Comment by ZizhuoWang** [comment]
我刚刚也遇到了一样的错误，我在今天零点之前想要清一波体力，于是点开了昨天的40AP狗粮本。因为我没有挂满破个人训练(御主经验增加10%)礼装的好友，所以我刷了一会好友列表想要找挂这个的大佬。好不容易找到一个，点击战斗开始，却没有意识到已经过了零点，周六的狗粮本已经关闭了。正常情况下FGO会提示任务尚未开放之类的，但是AnyProxy不知道这点，所以日志和客户端都报错。
AnyProxy日志的时间好像比咱们东八区慢8个小时，所以根据你的日志来看，你应该是0:34左右报的错，可能也是这个问题吧。

**Comment by ZizhuoWang** [comment]
```shell
[AnyProxy ERROR][2018-06-02 16:12:26]: TypeError: Cannot read property 'battle' of undefined
TypeError: Cannot read property 'battle' of undefined
    at Object.beforeSendResponse (/root/Anyproxy-fgo-rule/fgo.js:27:52)
    at beforeSendResponse.next (<anonymous>)
    at onFulfilled (/usr/lib/node_modules/anyproxy/node_modules/co/index.js:65:19)
    at /usr/lib/node_modules/anyproxy/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/usr/lib/node_modules/anyproxy/node_modules/co/index.js:50:10)
    at toPromise (/usr/lib/node_modules/anyproxy/node_modules/co/index.js:118:63)
    at next (/usr/lib/node_modules/anyproxy/node_modules/co/index.js:99:29)
    at onFulfilled (/usr/lib/node_modules/anyproxy/node_modules/co/index.js:69:7)
    at /usr/lib/node_modules/anyproxy/node_modules/co/index.js:54:5

```
同样的日志信息啊。哈哈哈

**Comment by LiuZHolmes** [comment]
哈哈有点奇怪，但是我当时确实是下午出现的错误，日志里的时间就是本地的时间:(
btw,大佬都是直接给大号用了吗，我还在担心被封只敢用给小号测试下...

**Comment by ZizhuoWang** [comment]
emmm我用了一段时间了，我感觉只要战斗时间不是太短的话问题不大吧。。。
主要是我玩的都是石头号，所以封了再换个号就是了。我的主号也是石头号，只是比较好的是有三拐。然后三拐石头号嫖其他石头号挂的我爆肝练的百级五宝三十打手😂然而现在在科技光环下谁都是三十五宝😂
关于fgo，我的乐趣也就是关了科技花式打打高难本，周回本就开科技清清ap，因为开着科技刷活动所以可以挂满加成不用担心打不过之类的。。。
怎么说呢，稍微有一点厨力的从者我就想要，但是又没钱氪金。所以每次出新从者或者限定从者的时候，我就会3块买个石头号，抽个五宝，练到满破看看卡面，刷满5羁绊听听语音什么的，也就心满意足了。。。特别喜欢的从者比如王哈桑、C狐等等，我还会去大神殿刷个结婚证什么的。
我的日志之所以慢8小时可能因为我是在docker里跑的，所以时区可能是默认的时区吧。。。

**Comment by LiuZHolmes** [comment]
那可能不关时间的事了，毕竟我那次出错是一个普普通通的狗粮本，没有你说的那种刚好跨天出错的情况。应该是其它原因了。 🤣

**Comment by Attt** [comment]
@LiuZHolmes @ZizhuoWang undefined这个是脚本的原因，已经修复了。
